apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/x86-unix/argocd.git
    targetRevision: master
    path: ./overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
